### ISSUE TITLE
Connect to node problem

### ISSUE THREAD

**Issue by mieszacz** [CityOfZion/neo-python#1039]
Hi,
after I run np-prompt I receive this message:

ohhh, some error we didn't expect happened. Please create a Github issue and share the following stacktrace so we can try to resolve it

----------------[start of trace]----------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/neo/Network/nodemanager.py", line 335, in _connect_to_node
    await asyncio.wait_for(connect_coro, timeout)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()                                                                                           
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection                               
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1068, in _create_connection_transport
    protocol = protocol_factory()
  File "/usr/local/lib/python3.8/dist-packages/neo/Network/protocol.py", line 22, in __init__
    self._stream_reader = StreamReader()
AttributeError: can't set attribute
----------------[end of trace]----------------

**Comment by ixje** [comment]
please fill in the full issue form. There is now too little information to try and help you

**Comment by ixje** [comment]
inactive
