### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__plyvel)

### ISSUE THREAD

**Issue by hzla** [CityOfZion/neo-python#134]
Hi, 

I've run into an issue while following the install instructions for OSX with Python 3.5. I've installed leveldb with brew and successfully installed the requirements with pip with no errors outputted. However, when I ran:
 
`python prompt.py`

i received the following output:

```
Traceback (most recent call last):
  File "prompt.py", line 25, in <module>
    from neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain import LevelDBBlockchain
  File "/Users/andylee/Desktop/Repos/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 2, in <module>
    import plyvel
  File "/Users/andylee/Desktop/Repos/neo-python/venv/lib/python3.5/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/Users/andylee/Desktop/Repos/neo-python/venv/lib/python3.5/site-packages/plyvel/_plyvel.cpython-35m-darwin.so, 2): Symbol not found: __ZTIN7leveldb10ComparatorE
  Referenced from: /Users/andylee/Desktop/Repos/neo-python/venv/lib/python3.5/site-packages/plyvel/_plyvel.cpython-35m-darwin.so
  Expected in: dynamic lookup
```
I followed the recommended solution and uninstalled plyvel and reinstalled with the recommended cflags

```
pip uninstall plyvel
CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip install --no-use-wheel plyvel --no-cache-dir --global-option=build_ext --global-option="-I/usr/local/Cellar/leveldb/1.20_2/include/" --global-option="-L/usr/local/lib"
```
Now when I run `python prompt.py` I am faced with the following 

```
Traceback (most recent call last):
  File "prompt.py", line 25, in <module>
    from neo.Implementations.Blockchains.LevelDB.LevelDBBlockchain import LevelDBBlockchain
  File "/Users/andylee/Desktop/Repos/neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 2, in <module>
    import plyvel
  File "/Users/andylee/Desktop/Repos/neo-python/venv/lib/python3.5/site-packages/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dynamic module does not define module export function (PyInit__plyvel)
```
Not quite sure where to go from here, and any help would be greatly appreciated!

**Comment by hzla** [comment]
Ok it seems that after uninstalling python from my system and reinstalling python 3.5 using Anaconda, the issue has been resolved. The problem may have been caused by conflicting Python versions.
