### ISSUE TITLE
ExecutionEngine.py - 'NoneType' object has no attribute 'GetBigInteger'

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#160]
I observed this while watching testnet sync on latest dev (2018-10)(92d517135a467577529299945c3beb7267ff32ce)

Could use some love to handle it more gracefully
```
[E 180110 13:38:04 ExecutionEngine:835] COULD NOT EXECUTE OP: 'NoneType' object has no attribute 'GetBigInteger' b'\x9f' LT
[E 180110 13:38:04 ExecutionEngine:836] 'NoneType' object has no attribute 'GetBigInteger'
    Traceback (most recent call last):
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 833, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 524, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'
```

**Comment by davemcphee** [comment]
Seems like failing fast and loud when VM encounters bad Op Codes seems like the correct behavior in this case.
