### ISSUE TITLE
Error when running prompt.py

### ISSUE THREAD

**Issue by eranartzi** [CityOfZion/neo-python#205]
Hey all,

Amazing job on NEO. I've been writing smart contracts on Ethereum for a while and Im really stoked about the possibility of using NEO and writing smart contracts in Python.

I followed the guide and when Im running prompt.py from the terminal with the command:
python3 prompt.py
or with
python3.5 prompt.py

Im getting the following error:
Traceback (most recent call last):
  File "prompt.py", line 25, in <module>
    from neo.Implementations.Wallets.peewee.UserWallet import UserWallet
  File "/Users/eranartzi/Desktop/NEO/neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 8, in <module>
    from neo.Wallets.Wallet import Wallet
  File "/Users/eranartzi/Desktop/NEO/neo-python/neo/Wallets/Wallet.py", line 25, in <module>
    from neocore.KeyPair import KeyPair
  File "/Users/eranartzi/anaconda2/envs/neo/lib/python3.5/site-packages/neocore/KeyPair.py", line 4, in <module>
    import scrypt
  File "/Users/eranartzi/anaconda2/envs/neo/lib/python3.5/site-packages/scrypt.py", line 11, in <module>
    _scrypt = cdll.LoadLibrary(imp.find_module('_scrypt')[1])
  File "/Users/eranartzi/anaconda2/envs/neo/lib/python3.5/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/Users/eranartzi/anaconda2/envs/neo/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/eranartzi/anaconda2/envs/neo/lib/python3.5/site-packages/_scrypt.cpython-35m-darwin.so, 6): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/eranartzi/anaconda2/envs/neo/lib/python3.5/site-packages/_scrypt.cpython-35m-darwin.so
  Reason: image not found

Anyone encountered this or knows why I am getting this error?

Im using a conda env instead of a venv by the way

Thanks!

**Comment by brainfvck** [comment]
I had same problem yesterday and solved by `brew reinstall openssl`

**Comment by eranartzi** [comment]
Nice!
Thanks @brainfvck. Solved
