### ISSUE TITLE
object of type 'UInt160' has no len()

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#229]
This appears to be a new bug introduced with the various merges/PRs from the past few days. The same issue occurs on both `master` and `development`.

If I revert to a9222a743ed6139846d3fbe98a9a9f8a1ebeb4d6 (last commit from Feb. 12), the smart contract compiles just fine.

If you need to test our code directly, you can find it here:

https://github.com/NarrativeNetwork/tokensale-neo-smartcontract/tree/master

```
[E 180215 21:19:40 ExecutionEngine:852] COULD NOT EXECUTE OP: object of type 'UInt160' has no len() b'h' SYSCALL
[E 180215 21:19:40 ExecutionEngine:853] object of type 'UInt160' has no len()
    Traceback (most recent call last):
      File ".../neo-python/neo/VM/ExecutionEngine.py", line 850, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File ".../neo-python/neo/VM/ExecutionEngine.py", line 218, in ExecuteOp
        if not self._Service.Invoke(call, self):
      File ".../neo-python/neo/VM/InteropService.py", line 308, in Invoke
        return func(engine)
      File ".../neo-python/neo/SmartContract/StateMachine.py", line 343, in Contract_Create
        engine.ScriptContainer.Hash if engine.ScriptContainer else None,
      File ".../neo-python/neo/Core/TX/Transaction.py", line 276, in Hash
        ba = bytearray(binascii.unhexlify(self.GetHashData()))
      File ".../neo-python/neo/Core/TX/Transaction.py", line 288, in GetHashData
        return Helper.GetHashData(self)
      File ".../neo-python/neo/Core/Helper.py", line 38, in GetHashData
        hashable.SerializeUnsigned(writer)
      File ".../neo-python/neo/Core/TX/Transaction.py", line 572, in SerializeUnsigned
        writer.WriteSerializableArray(self.Attributes)
      File ".../neo-python/venv/lib/python3.5/site-packages/neocore/IO/BinaryWriter.py", line 408, in WriteSerializableArray
        item.Serialize(self)
      File ".../neo-python/neo/Core/TX/TransactionAttribute.py", line 119, in Serialize
        length = len(self.Data)
    TypeError: object of type 'UInt160' has no len()
```

**Comment by brianlenz** [comment]
The other thing I'll mention is that we are using neo-boa 0.2.1 in order to work around https://github.com/CityOfZion/neo-boa/issues/35.

**Comment by localhuman** [comment]
closed in https://github.com/CityOfZion/neo-python/pull/237
