### ISSUE TITLE
Import contract_addr error

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#234]
This appears to be a relatively new issue on the latest `master` and `development` branches. There's an error when running `import contract_addr`. The contract exists, and it appears (?) the address is added successfully to the wallet, but this error happens.

```
neo> import contract_addr ea492d921336c468cd1603adb0d655097289b3ee 03fd99039dff3a731d47a7779df1e6edae67fdce4be1e02ab86aee47eb15091352
[I 180216 15:46:21 UserWallet:191] contract does not exist yet
Could not execute command: a bytes-like object is required, not 'str'
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File ".../neo-python/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 915, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "prompt.py", line 868, in run
    self.do_import(arguments)
  File "prompt.py", line 332, in do_import
    return ImportContractAddr(self.Wallet, arguments[1:])
  File ".../neo-python/neo/Prompt/Commands/LoadSmartContract.py", line 50, in ImportContractAddr
    wallet.AddContract(verification_contract)
  File ".../neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 197, in AddContract
    db_contract = Contract.create(RawData=contract.ToArray(),
  File ".../neo-python/neo/SmartContract/Contract.py", line 170, in ToArray
    return Helper.ToArray(self)
  File ".../neo-python/neo/Core/Helper.py", line 75, in ToArray
    value.Serialize(writer)
  File ".../neo-python/neo/SmartContract/Contract.py", line 159, in Serialize
    writer.WriteVarBytes(self.Script)
  File ".../neo-python/venv/lib/python3.5/site-packages/neocore/IO/BinaryWriter.py", line 356, in WriteVarBytes
    return self.WriteBytes(value, unhex=False)
  File ".../neo-python/venv/lib/python3.5/site-packages/neocore/IO/BinaryWriter.py", line 104, in WriteBytes
    return self.stream.write(value)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by jpankalainen** [comment]
Can't repro with the latest with the exact same input. Can you get the latest and verify that the issue still occurs? If so, can you give more accurate repro steps?

**Comment by localhuman** [comment]
closed in https://github.com/CityOfZion/neo-python/pull/237
