### ISSUE TITLE
Unhandled error when running docker image for the first time

### ISSUE THREAD

**Issue by asdullahsiddique** [CityOfZion/neo-python#238]
Step to reproduce
----

1. `git clone git@github.com:CityOfZion/neo-python.git`
2. `cd neo-python`
3. `docker build -t neoimg`
4. `docker run neoimg`

Description
---
When you build and run the [Docker file](https://github.com/CityOfZion/neo-python/blob/master/Dockerfile) for the first time it should start and get you in the neo prompt as the last command in `Dockerfile` is:  
`CMD python3 prompt.py`  

However an error is raised:

```
$ docker run neodocker          
[I 180219 07:56:02 LevelDBBlockchain:489] Could not get sys fee: 'NoneType' object is not subscriptable 
[I 180219 07:56:02 NotificationDB:76] Created Notification DB At /neo-python/Chains/Test_Notif 
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python3.5/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 829, in run
    print_tokens(tokens, self.token_style)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/shortcuts.py", line 698, in print_tokens
    output = create_output(true_color=true_color, stdout=file)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/shortcuts.py", line 126, in create_output
    ansi_colors_only=ansi_colors_only, term=term)
  File "/usr/local/lib/python3.5/dist-packages/prompt_toolkit/terminal/vt100_output.py", line 424, in from_pty
    assert stdout.isatty()
builtins.AssertionError: 

[I 180219 07:56:34 EventHub:89] [SmartContract.Execution.Success][2002] [54030ae64f0a6d24bfda562778e0f4c9f1e24ecc] [tx 1a328cdd53c7f1710b4006304e8c75236a9b18523f037cdf069a96f0d7f01379] [False]
```

**Comment by metachris** [comment]
Are you using Windows? What version?

**Comment by asdullahsiddique** [comment]
I am using macOS High Sierra (v. 10.13.2)

**Comment by metachris** [comment]
Same error also on the development branch (if you change it in the Dockerfile)?

**Comment by asdullahsiddique** [comment]
I've update `Dockerfile` to checkout to `development` branch after the repo has been cloned, but still the same error occurs.

```
FROM ubuntu:16.04

RUN apt-get update && apt-get -y install git python3-dev python3-pip libleveldb-dev libssl-dev man

RUN git clone --single-branch -b development https://github.com/CityOfZion/neo-python.git

WORKDIR neo-python

RUN pip3 install -r requirements.txt

CMD python3 prompt.py
```

**Comment by metachris** [comment]
Should be fine with the current Dockerfiles: https://github.com/CityOfZion/neo-python/tree/development/docker

If the issue persists, please reopen or create a new ticket.

**Comment by overqint** [comment]
Working Docker File:

```
# Dockerfile to create images running neo-python
# https://github.com/CityOfZion/neo-python/tree/master/docker
#
# Building an image of the current master branch (creates a Docker image called neopython):
#
#    $ docker build -f Dockerfile -t neopython .
#
# Building an image of the current development branch (creates a Docker image called neopython-dev):
#
#    $ docker build -t neopython-dev . --build-arg branch=development
#
# Build without caching:
#
#    $ docker build --no-cache -f Dockerfile -t neopython .
#
# Using with a private network
# -----------------------------
# If you want to run it connecting to a private network, make sure the privatenet container is already running.
# See also https://hub.docker.com/r/cityofzion/neo-privatenet
#
# Start a container interactively, opening a bash in `/neo-python`, and mounting the current directory as `/neo-python/sc`:
#
#    $ docker run --rm -it -v $(pwd):/neo-python/sc --net=host -h neopython --name neopython neopython /bin/bash
#
# Once you are inside the container, you can start neo-python with `np-prompt` (using -p to connect to a private net).
# To update neo-python, just run `git pull` and `pip install -e .`
FROM ubuntu:17.10

# Branch can be overwritten with --build-arg, eg: `--build-arg branch=development`
ARG branch=master

#change source location 
RUN sed -i 's|archive.ubuntu|old-releases.ubuntu|g' /etc/apt/sources.list
#security repos can not be updated and cause errors, remove them
RUN sed -i '/security.ubuntu.com/d' /etc/apt/sources.list

#run a quite update
RUN apt-get -qq update >> /dev/null 2>&1

# Install dependencies
RUN apt-get install -y \
    wget \
    git-core \
    python3.6 \
    python3.6-dev \
    python3.6-venv \
    python3-pip \
    libleveldb-dev \
    libssl-dev \
    vim \
    man

# APT cleanup to reduce image size
RUN rm -rf /var/lib/apt/lists/*

# Clone and setup
RUN git clone https://github.com/CityOfZion/neo-python.git
WORKDIR neo-python
RUN git checkout $branch

# Install the dependencies
RUN pip3 install -e .

# Download the privnet wallet, to have it handy for easy experimenting
RUN wget https://s3.amazonaws.com/neo-experiments/neo-privnet.wallet

# Example run command
CMD /bin/bash
```
