### ISSUE TITLE
New UserWallet throws TypeError: 'dict_values' object does not support indexing

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-python#243]
I'm creating a basic `UserWallet` as follows:
```
            wallet = UserWallet(self.wallet_path, self.wallet_pass, True)

            privKey = KeyPair.PrivateKeyFromWIF(wif)
            wallet.CreateKey(privKey)

            for token in NEP5Contracts:
                ImportToken(wallet, token)

            wallet.Close()
```
After I open it and run `wallet` I get this

```
[I 180220 22:09:56 UserWallet:531] Script hash b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9' <class 'bytes'>
Could not execute command: 'dict_values' object does not support indexing
  File "/usr/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/middleware/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 949, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "prompt.py", line 898, in run
    self.show_wallet(arguments)
  File "prompt.py", line 502, in show_wallet
    print("Wallet %s " % json.dumps(self.Wallet.ToJson(), indent=4))
  File "/home/middleware/neo/Implementations/Wallets/peewee/UserWallet.py", line 534, in ToJson
    token_balances = self.TokenBalancesForAddress(addr_str)
  File "/home/middleware/neo/Implementations/Wallets/peewee/UserWallet.py", line 459, in TokenBalancesForAddress
    '[%s] %s : %s' % (t.ScriptHash.ToString(), t.symbol, t.GetBalance(self, address, as_string=True))
  File "/home/middleware/neo/Wallets/NEP5Token.py", line 131, in GetBalance
    tx, fee, results, num_ops = test_invoke(sb.ToArray(), wallet, [])
  File "/home/middleware/neo/Prompt/Commands/Invoke.py", line 257, in test_invoke
    wallet_tx = wallet.MakeTransaction(tx=tx, from_addr=from_addr)
  File "/home/middleware/neo/Wallets/Wallet.py", line 1061, in MakeTransaction
    change_address = self.GetChangeAddress(from_addr=from_addr)
  File "/home/middleware/neo/Wallets/Wallet.py", line 900, in GetChangeAddress
    return self._contracts.values()[0]
TypeError: 'dict_values' object does not support indexing
```

This is the [broken_wallet](https://www.dropbox.com/s/g9p7b2fwqj7hz0g/broken_wallet?dl=0) file crated
password is `1231231231`

I'm on the latest development commit https://github.com/CityOfZion/neo-python/commit/1e40ea22b66a6560b2cf640013312d23f69e5743

I shortly debugged but no success yet. sleep now :(

**Comment by ixje** [comment]
The quick fix is
```
return list(self._contracts.values())[0]
```

as `return self._contracts.values()[0]` apparently is only for [python2](https://stackoverflow.com/questions/3097866/access-an-arbitrary-element-in-a-dictionary-in-python#comment28476565_17085251)

Haven't tested further implications yet, but so far it seems to show some data

**Comment by ixje** [comment]
`NEO` and `NEOgas` don't show up under synced balances even though I have balance
```
"balances": {
                "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7": "46509.979",
                "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b": "100000000.0"
            }
```

rebuilding wallet doesn't help (tried 3+ times)

**Comment by ixje** [comment]
More clues. Switching to `neocore 0.3.4` fixes the problem.
