### ISSUE TITLE
Can't load existing wallet file with contracts

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#247]
I've got a wallet file I've been using successfully on a slightly older version of neo-python from a couple of weeks ago. I'm trying to test out a few of the fixes on the latest `development` branch and discovered the wallet file will not load. I was able to successfully upgrade the wallet file with `reencrypt_wallet.py`, but when I load it, I get:

```
Could not open wallet: Non-hexadecimal digit found
```

I added a bunch of debugging to try to track the issue down, including  a traceback to help with logging:

```
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 882, in _bootstrap
    self._bootstrap_inner()
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File ".../.pyenv/versions/3.5.4/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "...neo-python/venv/lib/python3.5/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 870, in run
    self.do_open(arguments)
  File "prompt.py", line 218, in do_open
    traceback.print_stack()
Traceback (most recent call last):
  File "prompt.py", line 211, in do_open
    self.Wallet = UserWallet.Open(path, password_key)
  File "...neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 124, in Open
    return UserWallet(path=path, passwordKey=password, create=False)
  File "...neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 43, in __init__
    super(UserWallet, self).__init__(path, passwordKey=passwordKey, create=create)
  File "...neo-python/neo/Wallets/Wallet.py", line 125, in __init__
    self._contracts = self.LoadContracts()
  File "...neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 299, in LoadContracts
    ctr[contract.ScriptHash.ToBytes()] = contract
  File "...neo-python/neo/Core/VerificationCode.py", line 23, in ScriptHash
    self._scriptHash = Crypto.ToScriptHash(self.Script, unhex=unhex)
  File "...neo-python/venv/lib/python3.5/site-packages/neocore/Cryptography/Crypto.py", line 85, in ToScriptHash
    data = binascii.unhexlify(data)
```

I also output the value of the script on which `unhexlify` is being called, and it's a byte array value, not hex, hence the error.

I believe it's caused by an incompatibility between these two changes:

https://github.com/CityOfZion/neo-python/commit/3173f030def0629a850f80e4020ed52616c1be79#diff-506426af169779585591f59071264b0bR20

https://github.com/CityOfZion/neo-python/commit/3173f030def0629a850f80e4020ed52616c1be79#diff-7dc76a378f4aa890f0a8cc4253e734e7R158

Ultimately, we're calling unhex on what is now a non-hex value because the length of the script isn't 35 bytes. I would fix, but I'm not positive on the appropriate solution.

cc: @localhuman, as I'm sure this will be more obvious to you :)

**Comment by brianlenz** [comment]
As you'd expect, it works just fine if I roll back to a version prior to the referenced commit.

**Comment by localhuman** [comment]
Will take a look!

**Comment by localhuman** [comment]
Recent pushes to dev should resolve your issue. LMK if you're still having problems.

**Comment by brianlenz** [comment]
Yep, works now! Thanks 👍
