### ISSUE TITLE
peewee latest version is 3.1.0 and breaks things (we're at 2.10.2)

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-python#262]
Just a note: the latest peewee release is 3.1.0, and we're on 2.10.2. Updating breaks things.
Errors look like this:

    File "/Users/chris/Projects/chris/neo/neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 124, in Open
        return UserWallet(path=path, passwordKey=password, create=False)
    File "/Users/chris/Projects/chris/neo/neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 43, in __init__
        super(UserWallet, self).__init__(path, passwordKey=passwordKey, create=create)
    File "/Users/chris/Projects/chris/neo/neo-python/neo/Wallets/Wallet.py", line 107, in __init__
        raise Exception("Password hash not found in database")
    Exception: Password hash not found in database

Just wanted to note that somewhere, if we don't plan to upgrade to 3.x then we can also close this issue.

**Comment by iNomaD** [comment]
Btw, `wallet rebuild` sometimes failes after the update to python3.6 on peewee 2.10.2.

```
neo> wallet rebuild
Could not execute command: database is locked
  File "E:\Programs\Anaconda3\envs\neo36\lib\threading.py", line 884, in _bootst
rap
    self._bootstrap_inner()
  File "E:\Programs\Anaconda3\envs\neo36\lib\threading.py", line 916, in _bootst
rap_inner
    self.run()
  File "E:\Programs\Anaconda3\envs\neo36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\_threads\_thr
eadworker.py", line 46, in work
    task()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\_threads\_tea
m.py", line 190, in doWork
    task()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\python\thread
pool.py", line 250, in inContext
    result = inContext.theWork()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\python\thread
pool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\python\contex
t.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\twisted\python\contex
t.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 922, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 3830
, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prompt.py", line 879, in run
    self.show_wallet(arguments)
  File "prompt.py", line 499, in show_wallet
    self.Wallet.Rebuild()
  File "e:\Blockchain\generion-middleware\neo\Implementations\Wallets\peewee\Use
rWallet.py", line 110, in Rebuild
    c.delete_instance()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 5217
, in delete_instance
    return self.delete().where(self._pk_expr()).execute()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 3614
, in execute
    return self.database.rows_affected(self._execute())
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 2939
, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 3837
, in execute_sql
    self.commit()
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 3656
, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 135,
 in reraise
    raise value.with_traceback(tb)
  File "E:\Programs\Anaconda3\envs\neo36\lib\site-packages\peewee.py", line 3830
, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: database is locked
```

**Comment by metachris** [comment]
This is a different error, please create a separate ticket for it.

**Comment by jseagrave21** [comment]
@metachris After changing the requirements.txt I was able to run neo-python on my private net with peewee-3.5.2 installed (this is the new latest version). I did not get the same errors as you when I tried to interact with wallets.

When I tried to open the privatenet wallet, I got this error:
[E 180708 15:29:51 UserWallet:334] Could not get key 'utf-8' codec can't decode byte 0xb4 in position 3: invalid start byte
Could not open wallet: Password hash not found in database

When I tried to create a wallet, I got this error:
Exception creating wallet: 'utf-8' codec can't decode byte 0x95 in position 2: invalid start byte

I googled errors like this and it looks like a unicode problem, but I don't know how to proceed from here. Any thoughts?

**Comment by jseagrave21** [comment]
@metachris @localhuman 
I was able to get peewee 3.5.2 to work but I had to edit peewee.py. This fixed all the errors. The error was occurring in class _StringField(Field). The original class looked like this:

```
class _StringField(Field):
    def adapt(self, value):
        if isinstance(value, text_type):
            return value
        elif isinstance(value, bytes_type):
            return value.decode("utf-8")
        return text_type(value)

    def __add__(self, other): return self.concat(other)
    def __radd__(self, other): return other.concat(self)

```
I changed it to look like this:

```
class _StringField(Field):
    def adapt(self, value):
        if isinstance(value, text_type):
            return value
        elif isinstance(value, bytes_type):
            try:
                return value.decode("utf-8")
            except UnicodeDecodeError:
                return value
        return text_type(value)

    def __add__(self, other): return self.concat(other)
    def __radd__(self, other): return other.concat(self)
```

Now if peewee cannot decode the byte array using utf-8, it will just return the value. I cannot create a pull request because I edited peewee.py itself. I am working to figured out a way for neo-python to return the value if there is a UnicodeDecodeError so I can create a pull-request, so I can get credit for working on this.

**Comment by jseagrave21** [comment]
@metachris @localhuman 

After further review, I don't think I can fix anything in /neo/ to be able to implement peewee 3.5.2. When I run test_create_user_wallet.py, every test fails. I traced the first test as shown below:

```
ERROR: test_1_initial_setup (neo.Implementations.Wallets.peewee.test_create_user_wallet.UserWalletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Implementations/Wallets/peewee/test_create_user_wallet.py", line 36, in test_1_initial_setup
    wallet = self.GetWallet1()
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Implementations/Wallets/peewee/test_create_user_wallet.py", line 31, in GetWallet1
    to_aes_key('awesomepassword'))
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Implementations/Wallets/peewee/UserWallet.py", line 142, in Create
    wallet = UserWallet(path=path, passwordKey=password, create=True)
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Implementations/Wallets/peewee/UserWallet.py", line 44, in __init__
    super(UserWallet, self).__init__(path, passwordKey=passwordKey, create=create)
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Wallets/Wallet.py", line 98, in __init__
    self.SaveStoredData('PasswordHash', passwordHash)
  File "/mnt/c/users/seagrave/neo-python-peewee/neo/Implementations/Wallets/peewee/UserWallet.py", line 364, in SaveStoredData
    k = Key.create(Name=key, Value=value)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 5393, in create
    inst.save(force_insert=True)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 5516, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 1560, in inner
    return method(self, database, *args, **kwargs)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 1631, in execute
    return self._execute(database)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2274, in _execute
    return super(Insert, self)._execute(database)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2049, in _execute
    cursor = database.execute(self)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2637, in execute
    sql, params = ctx.sql(query).query()
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 549, in sql
    return obj.__sql__(self)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2249, in __sql__
    self._simple_insert(ctx)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2146, in _simple_insert
    return self._generate_insert((self._insert,), ctx)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 2221, in _generate_insert
    return ctx.sql(CommaNodeList(all_values))
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 549, in sql
    return obj.__sql__(self)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 1476, in __sql__
    ctx.sql(self.nodes[n_nodes - 1])
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 549, in sql
    return obj.__sql__(self)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 1476, in __sql__
    ctx.sql(self.nodes[n_nodes - 1])
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 549, in sql
    return obj.__sql__(self)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 1202, in __sql__
    return ctx.value(self.value, self.converter)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 561, in value
    value = converter(value)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 3832, in db_value
    return value if value is None else self.adapt(value)
  File "/mnt/c/users/seagrave/neo-python-peewee/venv/lib/python3.6/site-packages/peewee.py", line 3965, in adapt
    return value.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 0: invalid start byte
```

You can see that after it tries to use SaveStoredData in UserWallet.py the program enters peewee.py and never exits. So, there isn't a fix I can see without actually changing peewee.py.

If I make the changes to peewee.py as shown in my previous comment every test passes.
Let me know what you think.

**Comment by jseagrave21** [comment]
@metachris @localhuman 

I have submitted a PR to peewee project to implement my fix, shown below:

https://github.com/coleifer/peewee/pull/1682

**Comment by jseagrave21** [comment]
@metachris @localhuman my PR for peewee was closed with this comment:

"If you're storing a byte array -- i.e., not UTF8-encoded text -- you should be using a BlobField."

My changes were not merged. 

I will look into updating the neo-python code to implement the use of 'Blobfields' instead. This should support the use of the latest peewee.

**Comment by jseagrave21** [comment]
Unless there is anything else outstanding, I think this issue is ready to be closed :)
