### ISSUE TITLE
pip install -r requirements.txt failing

### ISSUE THREAD

**Issue by navneetlakra** [CityOfZion/neo-python#330]
Get the following error while running pip install -r requirements.txt. I am running Python 3.6.4 and leveldb is already installed on Mac OSX El Capitan. OpenSSL v0.9.8.

Using cached Twisted-17.9.0.tar.bz2
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/incremental/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    Couldn't find index page for 'incremental' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777) -- Some packages may not be found!
    No local packages or working download links found for incremental>=16.10.1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fm/vdptw9y110zb8h0lljx706zm0000gn/T/pip-build-tajxta4_/Twisted/setup.py", line 21, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('incremental>=16.10.1')

**Comment by metachris** [comment]
What operating system are you using? The package is available here: https://pypi.python.org/pypi/incremental

Perhaps El Capitan is not supported anymore? Can you double-check in the incremental project?

**Comment by navneetlakra** [comment]
Hi Chris, I was finally able to set it up. Did a few things:
1. Downloaded the certificate from pypi website and used it with pip install
2. Upgraded openssl from 0.9.8 to 1.0.2 in my Mac
3. Export cppflags and ldflags
$ export CPPFLAGS="-I/opt/local/include"
$ export  LDFLAGS="-L/opt/local/lib" 

It worked after doing all these steps

3.

**Comment by navneetlakra** [comment]
Looks like it would not work on Mac though. Testnet sync is throwing bunch of errors.

**Comment by localhuman** [comment]
What kind of errors? They may be normal.

Testnet has a lot of bad contract operations, and seeing errors in their execution is fairly normal.

**Comment by navneetlakra** [comment]
oh, ok. I will let it sync then. Almost 50% done now.

I am seeing messages like these:
[E 180318 10:41:24 ExecutionEngine:924] (69) VMFault.SYSCALL_ERROR
     [E 180318 10:41:27 ExecutionEngine:924] (69) VMFault.SYSCALL_ERROR
[E 180318 10:41:27 ExecutionEngine:829] COULD NOT EXECUTE OP (136): 'NoneType' object has no attribute 'GetBigInteger' b'\x9f' LT
[E 180318 10:41:27 ExecutionEngine:830] 'NoneType' object has no attribute 'GetBigInteger'
    Traceback (most recent call last):
      File "/Users/sangeetalakra/Documents/navneet/neo-python/neo/VM/ExecutionEngine.py", line 821, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/neo/VM/ExecutionEngine.py", line 511, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()                                                                                                                                            
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'
[E 180318 10:41:27 ExecutionEngine:829] COULD NOT EXECUTE OP (136): 'NoneType' object has no attribute 'GetBigInteger' b'\x9f' LT
[E 180318 10:41:27 ExecutionEngine:830] 'NoneType' object has no attribute 'GetBigInteger'
    Traceback (most recent call last):
      File "/Users/sangeetalakra/Documents/navneet/neo-python/neo/VM/ExecutionEngine.py", line 821, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/sangeetalakra/Documents/navneet/neo-python/neo/VM/ExecutionEngine.py", line 511, in ExecuteOp
        x2 = estack.Pop().GetBigInteger()
    AttributeError: 'NoneType' object has no attribute 'GetBigInteger'
[E 180318 10:41:27 ExecutionEngine:924] (53) VMFault.SYSCALL_ERROR
[E 180318 10:41:27 ExecutionEngine:924] (53) VMFault.SYSCALL_ERROR
[E 180318 10:41:27 ExecutionEngine:924] (53) VMFault.SYSCALL_ERROR
     [I 180318 10:41:48 NotificationDB:209] persist new NEP5 contract: b'ffde6a0d2d5319807176b9d6084b5e4f8dc81544' 
     [E 180318 10:42:43 ExecutionEngine:924] (53) VMFault.SYSCALL_ERROR
     [E 180318 10:42:55 ExecutionEngine:587] Could not checksig: 'NoneType' object has no attribute 'GetMessage' 
[E 180318 10:42:55 ExecutionEngine:587] Could not checksig: 'NoneType' object has no attribute 'GetMessage' 
[E 180318 10:42:55 ExecutionEngine:587] Could not checksig: 'NoneType' object has no attribute 'GetMessage'

**Comment by ixje** [comment]
@navneetlakra , as @localhuman said that's normal because there are a lot of bad contract executions on the testnet. Nothing to worry about :)

**Comment by navneetlakra** [comment]
Thanks for your help on this guys. Finally was able to setup the neo-python node.
