### ISSUE TITLE
Smart contract event handler current block lookup issue

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-python#424]
### Current behavior

- What is the problem?

(Original conversation: https://github.com/CityOfZion/neo-python/pull/381#issuecomment-390371960)

Smart contract event handlers can't look up the current block being processed via `Blockchain.GetHeaderByHeight()`. The `hash` is properly identified by `height`:

https://github.com/CityOfZion/neo-python/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L479

But the lookup of the block by `hash` fails:

https://github.com/CityOfZion/neo-python/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L442

That line is resulting in an error:

```
[I 180519 10:35:56 LevelDBBlockchain:449] TypeError in GetHeader 'NoneType' object is not iterable 
  File "handler.py", line 299, in <module>
    main()
  File "handler.py", line 295, in main
    event_handler.run()
  File "main.py", line 72, in run
    reactor.run()
  File "neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "neo-python/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "neo-python/venv/lib/python3.6/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "neo-python/venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 847, in PersistBlocks
    self.Persist(block)
  File "neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 825, in Persist
    events.emit(event.event_type, event)
  File "neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 282, in emit
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 282, in <listcomp>
    remove = [l for l in listeners if not l(*args, **kwargs)]
  File "neo-python/venv/lib/python3.6/site-packages/pymitter/__init__.py", line 310, in __call__
    self.func(*args, **kwargs)
  File "neo-python/neo/contrib/smartcontract.py", line 63, in call_on_event
    [event_handler(sc_event) for event_handler in handlers]
  File "neo-python/neo/contrib/smartcontract.py", line 63, in <listcomp>
    [event_handler(sc_event) for event_handler in handlers]
  File "handler.py", line 87, in sc_notify
    self.do_sc_notify(event)
  File "handler.py", line 158, in do_sc_notify
    block = self.blockchain.GetHeaderByHeight(block_number)
  File "neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 489, in GetHeaderByHeight
    return self.GetHeader(hash)
  File "neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 450, in GetHeader
    traceback.print_stack()
Traceback (most recent call last):
  File "neo-python/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py", line 444, in GetHeader
    out = bytearray(self._db.get(DBPrefix.DATA_Block + hash))
TypeError: 'NoneType' object is not iterable
```

(Here's the code that is running, which is why this traceback is appearing: https://github.com/brianlenz/neo-python/compare/42e0bb41866d0b2c7aa3ee460a8f8ce3ae2f1f22...brianlenz:7f5535fa90d3e20cff9318909ea4faa5d3765ae4)

This error indicates that the `self._db.get()` is returning `None`. Is this because the `write_batch` hasn't committed before the events are emitted and executed here?

https://github.com/CityOfZion/neo-python/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.py#L816

That seems to be clearly what the issue is, but I've not had luck as of yet tracking down what changed in the last couple of months that would have caused this issue to arise.

### Expected behavior

- What should be happening?

`Blockchain.GetHeaderByHeight()` should work for the current block in the context of a smart contract event handler.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

Set up a smart contract event handler that calls `Blockchain.GetHeaderByHeight()` for the event's block.

### Your environment

Let us know in what environment you're running into the issue:

- OS: Debian 8
- neo-python version: 0.6.9
- Python version: 3.6.5rc1

**Comment by brianlenz** [comment]
I've got what I believe to be the fix for this. Still haven't identified the origin of the issue, but the fix should solve it nonetheless. PR incoming...
