### ISSUE TITLE
Cannot run np-prompt --coznet -v 

### ISSUE THREAD

**Issue by stanleywijaya** [CityOfZion/neo-python#484]
### Current behavior

When i run 'np-prompt --coznet -v'.. I got this error:

Traceback (most recent call last):
  File "/home/vagrant/neo/neo-python/venv/bin/np-prompt", line 11, in <module>
    load_entry_point('neo-python', 'console_scripts', 'np-prompt')()
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/vagrant/neo/neo-python/neo/bin/prompt.py", line 28, in <module>
    from neo.Implementations.Wallets.peewee.UserWallet import UserWallet
  File "/home/vagrant/neo/neo-python/neo/Implementations/Wallets/peewee/UserWallet.py", line 8, in <module>
    from neo.Wallets.Wallet import Wallet
  File "/home/vagrant/neo/neo-python/neo/Wallets/Wallet.py", line 13, in <module>
    from Crypto.Cipher import AES
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 3, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/home/vagrant/neo/neo-python/venv/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 32, in <module>
    from Crypto.Util.py3compat import byte_string
**ImportError: cannot import name 'byte_string'**

I see in the file _raw_api.py that we dont have 'byte_string' function.
How can we solve this?

- OS: Windows running VM
- Python version: python3.6.6

**Comment by stanleywijaya** [comment]
I just re-install everything again.
It fixed now.

**Comment by metachris** [comment]
Thanks for he update.
