### ISSUE TITLE
Problems occurred when using JSON RPC API's

### ISSUE THREAD

**Issue by SabarishT** [CityOfZion/neo-python#505]
We have deployed a python contract in the Neo Blockchain

Contract Code in python :
`
   def Main(operation, a, b):

    if operation == 'add':
        return a + b

    elif operation == 'sub':
        return a - b

    elif operation == 'mul':
        return a * b

    elif operation == 'div':
        return a / b

    else:
        return -1`
		
Initially we have tested in the neo gui-2.6.6. We got correct output for input {add, 3, 4}

![neo capture](https://user-images.githubusercontent.com/29983995/42696902-3c62e40c-86d7-11e8-81fe-0b841d89c951.PNG)

Then we have tested in neo Python cmd in ubuntu-18.04 LTS

![sample22](https://user-images.githubusercontent.com/29983995/42697279-4b15f4e8-86d8-11e8-8b2a-f8c37520a418.PNG)

In the above two cases functionalities are working fine.

As the same way we have tested through postman, with the JSON RPC API's as given below
http://seed2.neo.org:20332, http://seed4.neo.org:20332, http://localhost:20332

**Request :**

> {
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0x86d58778c8d29e03182f38369f0d97782d303cc0",
    "Main",
    [
      {
        "type": "String",
        "value": "add"
      },
      {
        "type": "Integer",
        "value": 3
      },
      {
        "type": "Integer",
        "value": 4
      }
    ]
  ],
  "id": 1
}

**Response:**

> {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "script": "54530361646453c1044d61696e67c03c302d78970d9f36382f18039ed2c87887d586",
        "state": "FAULT, BREAK",
        "gas_consumed": "0.021",
        "stack": [
            {
                "type": "Array",
                "value": [
                    {
                        "type": "ByteArray",
                        "value": "4d61696e"
                    },
                    {
                        "type": "Array",
                        "value": [
                            {
                                "type": "ByteArray",
                                "value": "616464"
                            },
                            {
                                "type": "Integer",
                                "value": "3"
                            },
                            {
                                "type": "Integer",
                                "value": "4"
                            }
                        ]
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    }
                ]
            },
            {
                "type": "Integer",
                "value": "2"
            }
        ]
    }
}

Here we got the status ==> "state": "FAULT, BREAK",

Here we are not getting exact response as per neo gui-2.6.6.

Not only for this contract i am facing same type of response and empty responses for so many contracts using **PYTHON** and **JAVA** 

Kindly help us to move further

Thanks in advance 

Environment

- OS: Ubuntu-18.04 LTS And Windows -10
- neo-python version: 3.6+
- Python version: 3.6

**Comment by localhuman** [comment]
the `Main` function should not be included in your request, it will be called no matter what.

**Comment by SabarishT** [comment]
Without **Method** or **Main** function I am getting this response
![capture3](https://user-images.githubusercontent.com/29983995/42700012-1976e21e-86e0-11e8-97b7-112f72af4f81.PNG)

**Comment by ixje** [comment]
It appears this is not just a `neo-python` specific bug, but one that also exists in the C# version. I compared the C# implementation and we in `neo-python` do exactly the same as in C#.

Querying a C# node on the RPC port with your contract results in: 
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "525152c10361646467c03c302d78970d9f36382f18039ed2c87887d586",
        "state": "FAULT, BREAK",
        "gas_consumed": "0.021",
        "stack": [
            {
                "type": "Array",
                "value": [
                    {
                        "type": "ByteArray",
                        "value": "616464"
                    },
                    {
                        "type": "Array",
                        "value": [
                            {
                                "type": "Integer",
                                "value": "1"
                            },
                            {
                                "type": "Integer",
                                "value": "2"
                            }
                        ]
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    },
                    {
                        "type": "Boolean",
                        "value": false
                    }
                ]
            },
            {
                "type": "Integer",
                "value": "2"
            }
        ]
    }
}
```
It would be best to report this on the official project first (https://github.com/neo-project/neo/issues) and link to this issue so we can track their solution. Afterwards we can solve it in `neo-python`

**Comment by ixje** [comment]
For future resolving reference:
neo-python actually throws this error
```
[E 180715 10:42:59 ApplicationEngine:262] COULD NOT EXECUTE OP (23): Invalid list operation b'z' ROLL
[E 180715 10:42:59 ExecutionEngine:948] Invalid list operation
    Traceback (most recent call last):
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 939, in StepInto
        self.ExecuteOp(op, self.CurrentContext)
      File "/Users/erik/Documents/code/neo-python/neo/VM/ExecutionEngine.py", line 306, in ExecuteOp
        estack.PushT(estack.Remove(n))
      File "/Users/erik/Documents/code/neo-python/neo/VM/RandomAccessStack.py", line 64, in Remove
        raise Exception("Invalid list operation")
    Exception: Invalid list operation
```

I investigated the differences from `testinvoke` vs rpc invoked and you'll see we do not pack the arguments in `testinvoke` but we do in the `rpc invoke` (see below). We eventually get a list index out of bounds on the `ROLL` list access a bunch of instructions later.

*testinvoke*
```
1 PUSH2
2 PUSH1
3 PUSHBYTES3
4 APPCALL
```

*RPC invoked*
```
1 PUSH2
2 PUSH1
3 PUSH2 <- diff
4 PACK <- diff
5 PUSHBYTES3
6 APPCALL
```

**Comment by SabarishT** [comment]
@ixje Thanks for your help. This issue has been posted in official forum Here is the link https://github.com/neo-project/neo-cli/issues/199

**Comment by katiaabela** [comment]
Any updates on this issue please? I too am experiencing differences between testinvoke and the same using the JSON RPC API (it fails with the latter, but I get a correct result with the former). Did anyone find a possible workaround?

**Comment by Tommo-L** [comment]
Sorry,  the  JSON-RPC `invokefunction`  method can not invoke `Main` method, but the `operation`  defined in `Main` method, as the JSON-RPC `invokefunction` use the `Main` function as the entry point.

So, you should change the following:
```json
{
    "jsonrpc":"2.0",
    "method":"invokefunction",
    "params":[
        "0x86d58778c8d29e03182f38369f0d97782d303cc0",
        "Main",
        [
            {
                "type":"String",
                "value":"add"
            },
            {
                "type":"Integer",
                "value":3
            },
            {
                "type":"Integer",
                "value":4
            }
        ]
    ],
    "id":1
}
```
to:

```json
{
    "jsonrpc":"2.0",
    "method":"invokefunction",
    "params":[
        "0x86d58778c8d29e03182f38369f0d97782d303cc0",
        "add",
        [
            {
                "type":"Integer",
                "value":3
            },
            {
                "type":"Integer",
                "value":4
            }
        ]
    ],
    "id":1
}
```

**Comment by ixje** [comment]
no activity on the main repo issue https://github.com/CityOfZion/neo-python/issues/505#issuecomment-405179217
