### ISSUE TITLE
np-prompt invalid syntax

### ISSUE THREAD

**Issue by benjyz** [CityOfZion/neo-python#513]
```
$ np-prompt
Traceback (most recent call last):
  File "/Users/ben/nos/neo-python/venv/bin/np-prompt", line 11, in <module>
    load_entry_point('neo-python', 'console_scripts', 'np-prompt')()
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ben/nos/neo-python/neo/bin/prompt.py", line 23, in <module>
    from neo.Core.Blockchain import Blockchain
  File "/Users/ben/nos/neo-python/neo/Core/Blockchain.py", line 5, in <module>
    from neo.Core.Block import Block
  File "/Users/ben/nos/neo-python/neo/Core/Block.py", line 5, in <module>
    from neo.Core.BlockBase import BlockBase
  File "/Users/ben/nos/neo-python/neo/Core/BlockBase.py", line 6, in <module>
    from neo.Core.Helper import Helper
  File "/Users/ben/nos/neo-python/neo/Core/Helper.py", line 10, in <module>
    from neo.SmartContract.ApplicationEngine import ApplicationEngine
  File "/Users/ben/nos/neo-python/neo/SmartContract/ApplicationEngine.py", line 4, in <module>
    from neo.VM.ExecutionEngine import ExecutionEngine
  File "/Users/ben/nos/neo-python/neo/VM/ExecutionEngine.py", line 13, in <module>
    from neo.Prompt.vm_debugger import VMDebugger
  File "/Users/ben/nos/neo-python/neo/Prompt/vm_debugger.py", line 5, in <module>
    from boa.compiler import Compiler
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/boa/compiler.py", line 2, in <module>
    from boa.code.module import Module
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/boa/code/module.py", line 2, in <module>
    from boa.code.method import method as BoaMethod
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/boa/code/method.py", line 3, in <module>
    from boa.code.expression import Expression
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/boa/code/expression.py", line 6, in <module>
    import astor
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/astor/__init__.py", line 14, in <module>
    from .code_gen import to_source  # NOQA
  File "/Users/ben/nos/neo-python/venv/lib/python3.7/site-packages/astor/code_gen.py", line 311
    def visit_FunctionDef(self, node, async=False):
                                          ^
SyntaxError: invalid syntax
```

**Comment by localhuman** [comment]
This issue occurs when running on Python 3.7, which is not yet fully supported.
