### ISSUE TITLE
`make test` fails on a fresh clone of neo-python development branch

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neo-python#631]
### Current behavior
I downloaded a fresh clone of the development branch and ran `make test` and received these errors:
```
======================================================================
FAIL: test_1_no_available_claim (Prompt.Commands.tests.test_claim_command.UserWalletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-dev/neo/Prompt/Commands/tests/test_claim_command.py", line 72, in test_1_no_available_claim
    self.assertEqual(Fixed8.FromDecimal(0.0002685), unavailable_bonus)
AssertionError: <neocore.Fixed8.Fixed8 object at 0x7fc856aeaac8> != <neocore.Fixed8.Fixed8 object at 0x7fc856ac0208>

======================================================================
FAIL: test_2_wallet_with_claimable_gas (Prompt.Commands.tests.test_claim_command.UserWalletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-dev/neo/Prompt/Commands/tests/test_claim_command.py", line 92, in test_2_wallet_with_claimable_gas
    self.assertEqual(Fixed8.FromDecimal(0.000601), unavailable_bonus)
AssertionError: <neocore.Fixed8.Fixed8 object at 0x7fc8590c6e10> != <neocore.Fixed8.Fixed8 object at 0x7fc856b39da0>

======================================================================
FAIL: test_get_bestblockhash (api.JSONRPC.test_json_rpc_api.JsonRpcApiTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-dev/neo/api/JSONRPC/test_json_rpc_api.py", line 169, in test_get_bestblockhash
    self.assertEqual(res['result'], '0x62539bdf30ff2567355efb38b1911cc07258710cfab5b50d3e32751618969bcb')
AssertionError: '0x7d4761120d8e13d18b5e8c4b33d5bcea380b242e99148ee263bf218fae36f072' != '0x62539bdf30ff2567355efb38b1911cc07258710cfab5b50d3e32751618969bcb'
- 0x7d4761120d8e13d18b5e8c4b33d5bcea380b242e99148ee263bf218fae36f072
+ 0x62539bdf30ff2567355efb38b1911cc07258710cfab5b50d3e32751618969bcb


======================================================================
FAIL: test_prompt_run (bin.test_prompt.PromptTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-dev/neo/bin/test_prompt.py", line 14, in test_prompt_run
    self.assertIn(checktext, text)
AssertionError: 'neo>' not found in '\x1b[32m[I 180921 17:31:41 LevelDBBlockchain:113]\x1b[39m Created Blockchain DB at /home/jseagrave21/.neopython/Chains/SC234 \r\n'

----------------------------------------------------------------------
Ran 359 tests in 82.550s

FAILED (failures=4)
```

### Expected behavior

There should be no errors: I understand that test_prompt.py is being disabled (https://github.com/CityOfZion/neo-python/pull/628)

### How to reproduce

Download a fresh clone of the development branch and run `make test`

### Your environment

- OS: Windows 10 Pro
- neo-python version: neo-python v0.7.9-dev
- Python version: Python 3.6.5

**Comment by ixje** [comment]
the testing of `neo-python` itself actually goes right, but overall testing fails on `neo-boa` tests because those are pulled from `pip` and are still outdated (thus using fixtures v7 not v8)

@localhuman can you push do a `neo-boa` release? then we can update the `neo-python` requirements file and resolve this issue 👍

**Comment by jseagrave21** [comment]
Awesome, I figured it would be a pretty easy fix. I just noticed it while working on a different PR.

**Comment by ixje** [comment]
fixed
