### ISSUE TITLE
build_raw_transactions.py relies on an active blockchain node

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neo-python#717]
### Current behavior
_NOTE: This issue is carried over from an unresolved issue from #dev-general on Discord_

User @amir reported receiving this error while trying to build a raw transaction per the example:
```
Traceback (most recent call last):
  File "./neophone.py", line 229, in <module>
    NeoPhone()
  File "./neophone.py", line 52, in init
    getattr(self, parsed_args.command)(leftover_args)
  File "./neophone.py", line 157, in transfer
    neolib.transfer()
  File "/Users/amirbaer/Home/code/curv/repos/research/neo/python/neolib.py", line 124, in transfer
    context = ContractParametersContext(contract_tx)
  File "/usr/local/lib/python3.6/site-packages/neo/SmartContract/ContractParameterContext.py", line 83, in init
    self.ScriptHashes = verifiable.GetScriptHashesForVerifying()
  File "/usr/local/lib/python3.6/site-packages/neo/Core/TX/Transaction.py", line 721, in GetScriptHashesForVerifying
    raise Exception("Invalid operation")
Exception: Invalid operation
```

After investigating, I found the problem here:
https://github.com/CityOfZion/neo-python/blob/f003f0a66cdd10cef91f30a6cda5549844ebd013/neo/Core/TX/Transaction.py#L719-L721

### Expected behavior

Building a raw transaction to relay via RPC method `sendrawtransaction` should not rely on an active blockchain instance.

### How to reproduce

Run `example1` or `example2` without a blockchain db activate in the environment.

### Your environment

- OS: Windows 10 Pro
- neo-python version: v0.8.3.dev0
- Python version: 3.7

**Comment by jseagrave21** [comment]
This issue has been addressed! :tada:
