### ISSUE TITLE
Unable to import contract. Error: "Non-hexadecimal digit found"

### ISSUE THREAD

**Issue by eladelrom** [CityOfZion/neo-python#800]
### Current behavior
- Are you using the latest available version? If not, first update and verify the problem still exists.
On branch development, up to date.
- What is the problem?
Unable to import contract getting "Non-hexadecimal digit found".  See messages below;
```
neo> build smartContracts/sample1.py '' 01 False False False                                                                                                 
[I 190107 11:17:09 BuildNRun:54] Saved output to smartContracts/sample1.avm 
neo> import contract smartContracts/sample1.avm "" 01 False False False                                                                                      
Could not execute command: Non-hexadecimal digit found
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "~/Desktop/neo-python/venv/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "prompt.py", line 1079, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "prompt.py", line 1025, in run
    self.do_import(arguments)
  File "prompt.py", line 384, in do_import
    return self.load_smart_contract(arguments)
  File "prompt.py", line 824, in load_smart_contract
    function_code = LoadContract(args[1:])
  File "~/Desktop/neo-python/neo/Prompt/Commands/LoadSmartContract.py", line 70, in LoadContract
    for p in binascii.unhexlify(params):
binascii.Error: Non-hexadecimal digit found
```
- Include a screenshot if it makes sense.

### Expected behavior

- What should be happening?
Prompted to fill out properties about contract

- Include a screenshot if it makes sense.

### How to reproduce

- Please explain the steps to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of this project.

Create Hello World contract name it: sample1.py 
```
def Main():
  print("Hello World")
  return True
```

Build the contract:
```
neo> build smartContracts/sample1.py '' 01 False False False
```
Import
```
neo> import contract smartContracts/sample1.avm "" 01 False False False
```
### Your environment

Let us know in what environment you're running into the issue:

- OS: (Windows version/Linux distro/OSX version) 
MacOS 10.14.2
- neo-python version: (hint: use `np-prompt --version`)
neo-python v0.8.3-dev
- Python version: (hint: `python -V`)
Python 3.6.6

**Comment by ixje** [comment]
Hi, 
Your issue has been fixed in the latest `development` branch pushed just moments ago. Please be aware that this latest version introduces changes to the cli commands. This means;
- `build` is now `sc build`
- `import` is now `sc deploy`

Please consult the `help` output of the individual commands for their usage as some input parameters might have changed order from the old commands.

**Comment by eladelrom** [comment]
I can confirm I was able to build and deploy as expected.   Thanks for the quick turn around.
