### ISSUE TITLE
Individual unittests fail locally

### ISSUE THREAD

**Issue by jseagrave21** [CityOfZion/neo-python#859]
### Current behavior
After the `classmethods` seen here https://github.com/CityOfZion/neo-python/commit/2d618455230b00586d9f6c4cabe075d4a08994f9 were removed, I can no longer successfully conducted individual unittests locally without receiving an error similar to the following:
```
======================================================================
ERROR: test_wallet_import_wif (neo.Prompt.Commands.tests.test_wallet_import_commands.UserWalletTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/tests/test_wallet_import_commands.py", line 41, in test_wallet_import_wif
    res = CommandWallet().execute(args)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/Wallet.py", line 69, in execute
    return self.execute_sub_command(item, arguments[1:])
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/CommandBase.py", line 75, in execute_sub_command
    return self.__sub_commands[id].execute(arguments)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/WalletImport.py", line 40, in execute
    return self.execute_sub_command(item, arguments[1:])
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/CommandBase.py", line 75, in execute_sub_command
    return self.__sub_commands[id].execute(arguments)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/WalletImport.py", line 54, in execute
    print("Please specify the required parameter")
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/PromptPrinter.py", line 49, in prompt_print
    pp.print(*args, **kwargs)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/PromptPrinter.py", line 42, in print
    self.printer(*args, **kwargs)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/PromptPrinter.py", line 36, in _internal_prompt_print
    print_formatted_text(*frags, **kwargs)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/venv/lib/python3.7/site-packages/prompt_toolkit/shortcuts/utils.py", line 94, in print_formatted_text
    output = create_output(stdout=file)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/venv/lib/python3.7/site-packages/prompt_toolkit/output/defaults.py", line 39, in create_output
    stdout, term=get_term_environment_variable())
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/venv/lib/python3.7/site-packages/prompt_toolkit/output/vt100.py", line 420, in from_pty
    fd = stdout.fileno()
io.UnsupportedOperation: fileno
```

Re-adding the `classmethods` mentioned above allows the individual unittests to pass; however, I am not sure if reverting the removal is the correct path since @ixje removed these methods purposefully.

cc @LysanderGG @metachris @localhuman 

### Expected behavior

Individual unittests should be able to pass locally.

### How to reproduce
clone v0.8.3 and run an individual unittest locally (e.g. `python -m unittest -v neo/Prompt/Commands/tests/test_wallet_import_commands.py`)

### Your environment

Let us know in what environment you're running into the issue:

- OS: Windows
- neo-python version: v0.8.3
- Python version: 3.7

**Comment by lock9** [comment]
I am having the same issue with other tests, `def test_GetHeaderBy(self):  ` is failing here

**Comment by ixje** [comment]
We use `prompt_toolkit` for console formatting/output. For a while it worked fine, then suddenly Travis-ci started throwing a "console is not a tty" error, even though it always worked before and even though travis runs an ubuntu image that should have a tty terminal. You see this same error if you run it with Pycharm on the emulated console. I tried to work around it for the time being because I had the [idea](https://github.com/CityOfZion/neo-python/issues/624) to move to another framework anyways. 

If you use `make test` it will set the `NEOPYTHON_UNITTEST` environment variable for the duration of the test, which ensures you use a regular `print()` call ([ref](https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/neo/Prompt/PromptPrinter.py#L40)) instead of the 'special' `print_formatted_text` from `prompt_toolkit` ([ref](https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/neo/Prompt/PromptPrinter.py#L36)) which does the TTY check. 

It is really a bandage solution until we move away.

**Comment by ixje** [comment]
you'll have to set the `NEOPYTHON_UNITTEST` environment variable to `1` if you're not running it from a tty (terminal).
