### ISSUE TITLE
[BUG] Decimal issue with claimable GAS from sys_fee

### ISSUE THREAD

**Issue by ThomasLobker** [CityOfZion/neo-python#902]
### Current behavior
All systems fees in transactions should be distributed to the NEO holders. In neo-python this becomes visible as unavailable GAS and after spending your NEO as available GAS to claim. If you have a wallet with 100M NEO inside, you should be getting the GAS of all systems fees. For example, if someone deploys a contract and spends 490 GAS then this GAS should become claimable in your wallet.

There seems to be a bug (in `neo-python` `0.8.4`) where the calculation of system fee distribution is ignoring the decimal. So for example if you have 32920 GAS as unavailable for claiming, and a 490 GAS contract is being deployed, the counter increases to 49000032920 GAS (instead of the expected 33410). Any claiming of GAS will now also fail because the amount in the claim transaction is wrong.

### Expected behavior
Correct incrementing of unavailable GAS for claiming in transactions with a `sys_fee`.

### How to reproduce
- Set up a private net
- Make sure you have a wallet with 100M NEO
- Wait until you can claim enough GAS to deploy a contract (490 GAS)
- Claim GAS and deploy a contract (spending 490 GAS on sys_fee)
- Type `wallet` to check your unavailable GAS balance in claims

### Your environment
- OS: Linux in Docker
- neo-python version: `0.8.4`
- Python version: `3.7`

**Comment by ixje** [comment]
Most likely related to https://github.com/CityOfZion/neo-python/pull/751 (and possibly https://github.com/CityOfZion/neo-python/pull/816). The former is the correct fix when comparing to the neo core [code](https://github.com/neo-project/neo/blob/b5bd56d9a789419fbb4bf861e3f373a2d6685b3f/neo/Network/P2P/Payloads/InvocationTransaction.cs#L17), so it is probably the result of an error propagation throughout the rest of the code.

I've confirmed the issue on `0.8.4`. Not not yet known

**Comment by ixje** [comment]
reproducing the bug via `neo-local` shows that the unclaimed gas according to the local `neo-scan` instance is correct. This means that deploying goes fine and doesn't add super high fees, but that this is a visual representation issue.

**Comment by ThomasLobker** [comment]
It effectively breaks the `wallet claim` functionality

```
neo> wallet claim                                                                                                                                                                                           
Could not execute command: argument out of range
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/app/neo/bin/prompt.py", line 218, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "/app/neo/bin/prompt.py", line 204, in run
    cmd.execute(arguments)
  File "/app/neo/Prompt/Commands/Wallet.py", line 68, in execute
    return self.execute_sub_command(item, arguments[1:])
  File "/app/neo/Prompt/CommandBase.py", line 75, in execute_sub_command
    return self.__sub_commands[id].execute(arguments)
  File "/app/neo/Prompt/Commands/Wallet.py", line 206, in execute
    return ClaimGas(PromptData.Wallet, True, from_addr_str, to_addr_str)
  File "/app/neo/Prompt/Commands/Wallet.py", line 339, in ClaimGas
    wallet.Sign(context)
  File "/app/neo/Wallets/Wallet.py", line 1209, in Sign
    signature = Helper.Sign(context.Verifiable, key)
  File "/app/neo/Core/Helper.py", line 67, in Sign
    hashdata = verifiable.GetHashData()
  File "/app/neo/Core/TX/Transaction.py", line 298, in GetHashData
    return Helper.GetHashData(self)
  File "/app/neo/Core/Helper.py", line 48, in GetHashData
    hashable.SerializeUnsigned(writer)
  File "/app/neo/Core/TX/Transaction.py", line 581, in SerializeUnsigned
    writer.WriteSerializableArray(self.outputs)
  File "/usr/local/lib/python3.6/dist-packages/neocore/IO/BinaryWriter.py", line 408, in WriteSerializableArray
    item.Serialize(self)
  File "/app/neo/Core/TX/Transaction.py", line 132, in Serialize
    writer.WriteFixed8(self.Value)
  File "/usr/local/lib/python3.6/dist-packages/neocore/IO/BinaryWriter.py", line 450, in WriteFixed8
    return self.WriteInt64(value.value)
  File "/usr/local/lib/python3.6/dist-packages/neocore/IO/BinaryWriter.py", line 259, in WriteInt64
    return self.pack('%sq' % endian, value)
  File "/usr/local/lib/python3.6/dist-packages/neocore/IO/BinaryWriter.py", line 118, in pack
    return self.WriteBytes(struct.pack(fmt, data), unhex=False)
struct.error: argument out of range
```

**Comment by ixje** [comment]
yeah it's a little bit deeper than just visual. The problem is that it persisted the sysfee value incorrectly in the local db :(
