### ISSUE TITLE
'TransactionInput' object should have method  'Size'

### ISSUE THREAD

**Issue by LuoRyan** [CityOfZion/neo-python#944]
@ixje 
### Current behavior
```python
class TransactionInput(SerializableMixin, EquatableMixin):
    pass

transaction = business_withdraw_transaction.transaction
transaction_input = transaction.inputs[0]
transaction_input.Size()
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
AttributeError: 'TransactionInput' object has no attribute 'Size'
```

### Expected behavior
```python
'TransactionInput' object should have method  'Size'
```

### How to reproduce
```python
https://github.com/CityOfZion/neo-python/blob/development/neo/Core/TX/Transaction.py#L168-L224
```

### Your environment
```python
- OS: OSX10.14.5
- neo-python version: 0.8.4
- Python version: 3.7
```

**Comment by jseagrave21** [comment]
@LuoRyan I was looking at this issue and I am a bit confused. The `TransactionInput` class exists within neo-python, however it is not used anywhere. Instead inputs are built from `CoinReference` objects. This confusion was mentioned in this [neo-project issue ](https://github.com/neo-project/neo/issues/245) but both the [documentation](https://docs.neo.org/en-us/sc/reference/fw/dotnet/neo/TransactionInput.html) and the class remained unchanged, which I can see may lead to some confusion.

I ran my own test and could not reproduce your results: Below is the test which was successful:
```
[IMPORTS OMITTED]

ctx_raw = b'800000014a4dfb91023b1b2086029e03af739d9ceab35fffa8d528de9a6fee3e62bbecbd0000019b7cffdaa674beae0f930ebe6085af9093e5fe56b34a5c220ccdcf6efc336fc50000c16ff286230067f97110a66136d38badc7b9f88eab013027ce4901fd04014099546819767644bbef323e428aab48c8801e66b8c7fb452dcd11205c13f5b198c9b37e9aa6808d6c3a74e50931d3413115e2a86a4a4a99fcae894219c092ca6340a0de35bc6c04c25b8f6cca46b91a35144db40fc94967293500f08c58df81f7c9ecb59cc13bcaca4d932e27a8d9a8204f48d488b6ccdfccd830c22bf4b7353dd64039346418372b541dfe7fdc99611bfc59cee881044da2912cb2404b885c6472310a2b771153e6a0022abb11aa41288ef98a2aed1bb42714fa6a1c6e85e415b8bb4045cc681dbe07155b554b0291f0352546223e49e3192c221249c29eb97651aec3c5f2f6adfc85a87cfdfef3a15d57391cf99190e8d80b01fcc1ebf8f48c745957f154210209e7fd41dfb5c2f8dc72eb30358ac100ea8c72da18847befe06eade68cebfcb9210327da12b5c40200e9f65569476bbff2218da4f32548ff43b6387ec1416a231ee821034ff5ceeac41acf22cd5ed2da17a6df4dd8358fcb2bfb1a43208ad0feaab2746b21026ce35b29147ad09e4afe4ec4a7319095f08198fa8babbe3c56e970b143528d2221038dddc06ce687677a53d54f096d2591ba2302068cf123c1f2d75c2dddc542557921039dafd8571a641058ccc832c5e2111ea39b09c0bde36050914384f7a48bce9bf92102d02b1873a0863cd042cc717da31cea0d7cf9db32b74d4c72c01b0011503e2e2257ae'
    ctx_id = b'4feb0081f9425cab84269127bef0a871a84d4408f09923d17ebb257cd231b362'  # see https://neoscan-testnet.io/transaction/4FEB0081F9425CAB84269127BEF0A871A84D4408F09923D17EBB257CD231B362

def test_tx_input_size(self):
        ms = MemoryStream(binascii.unhexlify(self.ctx_raw))

        reader = BinaryReader(ms)

        tx = Transaction.DeserializeFrom(reader)

        self.assertEqual(tx.ToArray(), self.ctx_raw)
        self.assertEqual(tx.Hash.ToBytes(), self.ctx_id)

        tx_input = tx.inputs[0]
        res = tx_input.Size()
        
        self.assertTrue(res)
        self.assertEqual(34, res)
        self.assertIsInstance(tx_input, CoinReference)
```

This leaves the question, why does the `TransactionInput` class exist at all? I don't have a good reason for this and would recommend removing it because there is no mention of a `TransactionInput` class that I could find in the neo-project. cc @ixje

**Comment by LuoRyan** [comment]
@jseagrave21 
```python
haha~ I got it. Thank you~~
I should use CoinReference to build transactions, not TransactionInput

#  Our own implementation of neo-python based on MySQL
        for unspent_transaction_output_list in pay_unspent_transaction_output_dict.values():
            for unspent_transaction_output in unspent_transaction_output_list:
                transaction_input = TransactionInput(UInt256.ParseString(unspent_transaction_output.tx_hash), unspent_transaction_output.tx_index)
                self.transaction.inputs.append(transaction_input)
```
> It's been renamed from TransactionInput to CoinReference

**Comment by ixje** [comment]
can this be closed?

**Comment by jseagrave21** [comment]
@ixje the only question I had remaining was if you would like me to submit a PR removing the `TransactionInput` class to try to avoid future confusion.

**Comment by ixje** [comment]
No we can leave it there because `neo-boa` depends on it
